export const pendingInvitation = [
    {
    "name":"John",
    "location":"USA",
    "fbName":"John",
    "request": true,
    "Roster":false,
    "friend":false,
    "image" : require("./images/photo.jpeg").default
},
    {
        "name":"Michal",
    "location":"England",
    "fbName":"Michal",
    "request": true,
    "Roster":false,
    "friend":false,
    "image" : require("./images/photo.jpeg").default
},
{
    "name":"Tony",
"location":"USA",
"fbName":"Tony",
"request": false,
    "Roster":true,
    "friend":false,
"image" : require("./images/photo.jpeg").default,
},
{
    "name":"Cris",
"location":"USA",
"fbName":"Cris",
"request": false,
    "Roster":true,
    "friend":false,
"image" : require("./images/photo.jpeg").default,
},
{
    "name":"Ben",
"location":"USA",
"fbName":"Ben",
"request": false,
    "Roster":false,
    "friend":true,
"image" : require("./images/photo.jpeg").default,
},
{
    "name":"Hello",
"location":"USA",
"fbName":"John",
"request": false,
    "Roster":false,
    "friend":true,
"image" : require("./images/photo.jpeg").default,
},
]
export const rosterInfo = [
    {
        "name":"Cris",
    "location":"USA",
    "fbName":"Cris",
    "request": false,
        "Roster":false,
        "friend":false,
    "image" : require("./images/photo.jpeg").default,
    },
    {
        "name":"Ben",
    "location":"USA",
    "fbName":"Ben",
    "request": false,
        "Roster":false,
        "friend":false,
    "image" : require("./images/photo.jpeg").default,
    },
    {
        "name":"Hello",
    "location":"USA",
    "fbName":"John",
    "request": false,
        "Roster":false,
        "friend":false,
    "image" : require("./images/photo.jpeg").default,
    },
]